# elasticsearch/config/elasticsearch.yml
cluster.name: "siem-cluster"
node.name: "siem-node-1"
network.host: 0.0.0.0
discovery.type: single-node

# Enable security features
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true

# Memory settings
bootstrap.memory_lock: true
ES_JAVA_OPTS: "-Xms512m -Xmx512m"

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network settings
http.port: 9200
transport.port: 9300

# Index settings
action.auto_create_index: true
index.number_of_shards: 1
index.number_of_replicas: 0

# Performance settings
indices.memory.index_buffer_size: "10%"
indices.queries.cache.size: "5%"
search.max_buckets: 10000

# Monitoring settings
xpack.monitoring.collection.enabled: true